services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    container_name: database
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TempDBPass1"
    ports:
      - "1433:1433"
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-U",
          "sa",
          "-P",
          "TempDBPass1",
          "-C",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      retries: 5
      start_period: 20s
    volumes:
      - database:/var/opt/mssql

  database-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database-init
    network_mode: service:database
    command: bash -c 'until /opt/mssql-tools18/bin/sqlcmd -S database -U sa -P TempDBPass1 -C -i ./db/init.sql; do echo retry && sleep 1; done'
    volumes:
      - ./db:/db
    depends_on:
      database:
        condition: service_healthy

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
    depends_on:
      database-init:
        condition: service_completed_successfully

volumes:
  database: